version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgres://postgres:123456@db:5432/modsenpractice'
      JWT_SECRET: 'ModsenPracticeDenisenkoDmitriy'
      JWT_REFRESH_SECRET: 'ModsenPracticeDenisenkoDmitriyRefreshToken'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: '123456'
      DB_DATABASE: 'modsenpractice'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DIALECT: 'postgres'
      PASS_SALT: '10'
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'modsenpractice'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
